"""
LPFullRangeCurve3pool Strategy Package.

Generated by: almanak strat new
"""

try:
    from .strategy import LPFullRangeCurve3poolStrategy
except ImportError:
    from strategy import LPFullRangeCurve3poolStrategy

__all__ = [
    "LPFullRangeCurve3poolStrategy",
]
